[package]
name = "knowit01"
version = "0.1.0"
authors = ["JonasJore <jonas.jore@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
