[package]
name = "aoc04"
version = "0.1.0"
authors = ["Jonas Jore <jonas.jore@sparebank1.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.10.3"